name: Scheduled CI

on:
  schedule:
    # Run every Monday at 10:00 AM ET (2:00 PM UTC)
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run build
        run: npm run build
      
      - name: Run tests
        run: npm test
        continue-on-error: true